// for the normal mode

const normalText = [
    "The big red house sits on a green hill, surrounded by tall trees and colorful flowers, while birds sing and butterflies flutter in the warm sunshine, creating a peaceful and picturesque scene.",
    "The large yellow sun shines above the calm blue sea, as children run and play on the soft sandy beach, building sandcastles and collecting seashells, while seagulls soar in the clear sky and waves gently crash along the shore, creating a joyful and idyllic summer day.",
    "The sky is blue with fluffy white clouds floating gently above, as children run and laugh on the green grass, while birds sing their cheerful songs and colorful flowers bloom, spreading their pleasant scent, creating a peaceful and joyful scene of nature's beauty and the simple pleasures of life.",
    "Once upon a time, on a scorching hot day, a thirsty crow was flying across the countryside in search of water. The sun blazed overhead, and the crow's throat felt parched and dry. It desperately needed a drink to quench its thirst. As the crow flew, it spotted a village below and decided to descend in the hope of finding some water. It flew over houses and trees until it came across a small pot in a courtyard. The crow landed near the pot and peered inside, only to find that it contained very little water at the bottom.",
    "Onc day, there was a little caterpillar named Charlie who lived in a colorful meadow. Charlie was curious about the world and eager to learn new things. One day, he decided to embark on a learning journey.Charlie encountered various insects and animals in the meadow who became his mentors and taught him valuable lessons. Mr. Bee taught him the importance of hard work and perseverance, while Mrs. Ladybug showed him the beauty of kindness and cooperation.",
    "Polly lived happily in a large tree, surrounded by the lush greenery of the forest. Her colorful feathers and playful nature made her a favorite among the other creatures in the forest. She entertained them with her amusing imitations, bringing joy and laughter to all.One day, as Polly was exploring the forest, she overheard a group of hunters planning to capture exotic birds from the forest and sell them in a distant city. Alarmed and concerned for her friends, Polly knew she had to take action.",
    "Ruby the rabbit and Terry the turtle were great friends who loved spending time together. One day, they decided to have a race. Ruby was confident in her speed, while Terry relied on his steady pace.As the race started, Ruby dashed ahead, while Terry slowly but steadily moved forward. Ruby felt certain of her victory and even took a break to eat some grass. But to her surprise, Terry began catching up.Ruby sprinted with all her might, desperate to regain the lead, but she failed to see a sharp turn in the path. She tumbled into a thicket of thorns and got stuck.",
    "In the vast savannah, a lion named Leo and a rabbit named Robbie became unlikely friends. During a severe drought, they worked together to find a hidden oasis. Leo's strength and Robbie's wit helped them discover the oasis, providing relief to the suffering animals. They became the guardians of the oasis, promoting unity and collaboration. Their story inspired others to value different strengths and work together to overcome challenges.",
    "Given the fact that cats often hunt mice, a curious cat called Tom and a clever mouse named Milo made friends in a cosy house. Milo had an idea: they could work together as a team to solve problems. They decided to stop talking and begin supporting one another. Together, they had some food and had fun times. As their bond grew, other animals began to observe their actions. Everyone learned from it that understanding and cooperation may make friends even when people are not alike.",
    "J.K. Rowling is well-known for her magical novel series, Harry Potter. They tell the story of Harry, a young wizard, and his experiences at Hogwarts School of Magic. He battles Voldemort, a malevolent wizard, finds the truth about his magical roots, and finds the value of friendship and love. These tales discuss values against vices, the importance of friendship, and the courage it takes to act morally. These stories are beloved by a large number of people worldwide, and they were even adapted into popular films.",
    "There once lived a curious youngster named Sam in a little town tucked away amid flowing rivers and rolling hills. Sam was a regular boy with a vivid imagination. He strolled across the verdant countryside every day, finding hidden gems and interacting with fascinating people.While meandering through the forest on a bright afternoon, Sam came across an enigmatic old book. Despite the aged and faded cover, the pages within were brimming with enchanted tales of far-off places and fascinating animals. Sam, intrigued, made the decision to set out on an adventure motivated by the tales in the book. Sam headed off to discover the mysteries of the magical forest that lay beyond the settlement, armed only with a feeling of curiosity and a rucksack. Along the route, he came upon"
]

export default normalText;